#!/usr/bin/env bash

# ln-host
# @arguments:
#   - hostname - string (must correspond to desired hostname in ./hosts)

HOST=`hostname`

if [[ ! -z "$1" ]]; then
  HOST=$1
fi

CONFIG="hosts/$HOST/configuration.nix"
# HARDWARE_CONFIG="hosts/$HOST/hardware-configuration.nix"

if [[ ! -e $CONFIG ]];
then
  echo "missing $CONFIG" >&2
  exit 1
fi

ln -sv "$PWD/$CONFIG" /etc/nixos/configuration.nix
